= The design of the `osynth` library

== The structure of a "synthesized object"

The Figure <<synthesizedObjectStructure>> shows how each synthesized object is structured.
[plantuml]

----
testdot
----

[plantuml]
[[synthesizedObjectStructure]]
.Synthesized Object Structure
----
hide empty members
top to bottom direction

class ObjectSynthesizer {
}
package "synthesized object" <<Rectangle>> {
    interface InvocationHandler {
    }
    interface "BiFunction<SynthesizedObject,Object[],Object>" as bf1 {
    }
    class "Class<?>" as cl1 {
    }
    interface "SynthesizedObject" as so1 {
      {abstract} +List<Class<?>> interfaces()
      {abstract} +MethodHandler methodHandlerFor(MethodSignature)
      {abstract} +Object fallbackObject()
    }
    interface "MethodHandler" as mh1 extends bf1 {
    }
    class "MethodSignature" as ms1 {
    }
}
package "inside a synthesized object" as inside <<Rectangle>> {
    interface "SynthesizedObject" as so2 {
    }
    class "Class<?>" as cl2 {
    }
    interface "MethodHandler" as mh2
    class "MethodSignature" as ms2
    package "interfaces" as intpkg <<Rectangle>> {
        class "InterfaceA" as int1 <<example>> {
        }
        class "InterfaceB" as int2 <<example>> {
        }
    }
    class "java.lang.reflect.Proxy" as proxy {
    }
    object actualObject
}
package "another fallback object" <<Rectangle>> {
    class "Object" as obj3 {
    }
}
ObjectSynthesizer ..right..> so1
ObjectSynthesizer ..right..> InvocationHandler
so1 "1" -right-> "*" mh1
so1 .right.> ms1
so1 "1" -left-> "*" cl1: interfaces
so1 "1" -down-> "1" so2: fallbackObject
so1 "1" *-up-> "1" InvocationHandler
InvocationHandler "1" -down-> "1" so1

so2 "1" .right..> "*" ms2
so2 "1" -right-> "*" mh2
so2 "1" -left-> "*" cl2: interfaces
actualObject .up.> so2
actualObject -up-> proxy
actualObject .up.> int1
actualObject .up.> int2
so2 "1" --down--> "1" obj3: fallbackObject

note as N1
A fallback object can be a SynthesizedObject or
a normal object
end note
N1 .up. inside
N1 .right. obj3
note as N2
An actual object extends/implements Proxy,
SynthesizedObject, and interfaces held by
SynthesizedObject
end note
N2 .up. actualObject
----

Roughly speaking, when a method handling request comes into a synthesized object, it tries to find an appropriate handler from registered method handlers and then from `default` methods of registered interfaces.
If nothing is found, then the request will be delegated to a fallback object.
If the fallback object is another synthesized object, the handler searching procedure will be repeated on that synthesized project.

Once the control goes into a fallback object, it will not go out from the object.

=== `ObjectSynthesizer` class

A builder class to synthesize an object from given method handlers, interfaces, and a fallback object.
(t.b.d.)

=== `SynthesizedObject` interface

(t.b.d.)

=== `MethodHandler` interface

(t.b.d.)

=== `MethodSignature` class

(t.b.d.)

=== Important Core Java API classes

==== `java.lang.reflect.Proxy`

(t.b.d.)

==== `java.lang.reflect.InvocationHandler` interface

(t.b.d.)

== Method Dispatching Mechanism

A method invocation can be handled in three ways.

1. Search for a method handler.
2. If an appropriate method handler is not found, `default` method is searched.
3. If any `default` method is not found, then the request is delegated to "fallback object".

These are executed in this order one by one.
Throughout these steps, methods are identified by its name and parameter types *only* and their declaring classes and returning types do not matter.
That is, even if a method invocation happens for `InterfaceA#methodA(String)`, it might be handled by a `default` method defined as `InterfaceB#methodA(String)`.
In case the returning type does not match with the calling side intended (in the case above, suppose that the `InterfaceA#methodA(String)` is returning `int`, but the `InterfaceB#methodA(String)` is returning `Set<Integer>`), it will result in a runtime error.

=== Method Signature

A `MethodSignature` is a class designed to identify a method call destination.
It consists of a name of a method and a list of parameter types (`Class` es).
It is used as a key of a map to store method handlers (`MethodHandler` s).

=== Method Handlers

A `MethodHandler` class is extending a `BiFunction<SynthesizedObject, Object[], Object>>`.
`SynthesizedObject` is a proxy object which the `osynth` library forces every synthesized object to implement.
It has some convenient methods to access the framework level information, such as `interfaces()`, `fallbackObject()`, and `methodHandlers`.

=== `default` methods

(t.b.d.)

=== The fall-backing mechanism

When no appropriate way to handle a method call is found in the current synthesized object, the `osynth` delegates the procedure to its "fallback object".
The fallback object might be either a conventional Java object or another synthesized object.
The delegation happens using a reflection.
The current synthesized object tries to find a method by name and parameter types in the fallback object.

== References

- [[Proxy, 1]] "Proxy (Java Platform SE 8)" https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Proxy.html